"""Write generated tickets to disk as implementation-ready Markdown.

Each ticket becomes its own file (for example ``MVP-001.md``) carrying the user
story, acceptance criteria, and definition of done, so it can be handed straight
to an AI coding agent. A starter ``AGENTS.md`` captures the build conventions once
so the agent does not need them repeated in every prompt (spec-driven development).
"""
from __future__ import annotations

from pathlib import Path
from typing import List, Union

from app.models import JiraTicket


def _format_points(story_points: float) -> str:
    """Render 8.0 as '8' but keep 2.5 as '2.5'."""
    return str(int(story_points)) if float(story_points).is_integer() else str(story_points)


def render_ticket_md(ticket: JiraTicket) -> str:
    """Render one ticket as an implementation-ready Markdown spec."""
    meta = f"**Priority:** {ticket.priority}"
    if ticket.story_points is not None:
        meta += f"  |  **Story points:** {_format_points(ticket.story_points)}"

    lines = [
        f"# {ticket.key}: {ticket.title}",
        "",
        meta,
        "",
        f"**Suggested branch:** `{ticket.suggested_branch}`",
        "",
        "## User story",
        ticket.user_story,
        "",
        "## Description",
        ticket.description,
        "",
        "## Acceptance criteria",
        *[f"- [ ] {c}" for c in ticket.acceptance_criteria],
        "",
        "## Definition of done",
        *[f"- [ ] {d}" for d in ticket.definition_of_done],
        "",
    ]
    return "\n".join(lines)


def starter_agents_md(domain: str) -> str:
    """A starter AGENTS.md so an agent knows the build conventions without being told each time."""
    return f"""# AGENTS.md - how to build in this project

Conventions for any AI coding agent working here. Read this before implementing a ticket.

## What this project is
An MVP in the **{domain}** domain, built one ticket at a time. Each ticket is a
Markdown file in this folder (for example `MVP-001.md`) with its own acceptance criteria.

## How to implement a ticket
1. Read the ticket file. Build only what its acceptance criteria require - nothing more.
2. Write a test for each acceptance criterion FIRST, then implement until every test passes.
3. Keep it simple: one small web framework, store data in a local file (JSON or SQLite) for
   the MVP. Do not add authentication, databases, or third-party integrations until a ticket asks.
4. Run the full test suite before finishing. Never delete or weaken a test to make it pass.

## Safety and quality
- Never add a package without confirming it really exists.
- Never turn on auto-approve / "YOLO" mode.
- Validate input; never hard-code secrets.
- This is the {domain} domain: do not give medical, legal, or financial advice, and handle
  any personal data carefully.

## Shipping
- Commit with a clear message and open a **draft** pull request. A human reviews every change;
  never auto-merge.
"""


def render_index_md(tickets: List[JiraTicket]) -> str:
    """A small index so the folder explains itself."""
    example_key = tickets[0].key if tickets else "MVP-001"
    lines = [
        "# Tickets",
        "",
        "Generated by MVPFlow AI. Each file is one implementation-ready ticket with acceptance criteria.",
        "",
        "Hand one to your AI coding agent (in Agent mode):",
        "",
        f"> Implement `{example_key}.md`, test-first. Follow `AGENTS.md`. Then open a draft pull request.",
        "",
        "## Backlog",
        *[f"- [{t.key}]({t.key}.md): {t.title}" for t in tickets],
        "",
    ]
    return "\n".join(lines)


def write_tickets(tickets: List[JiraTicket], out_dir: Union[str, Path], domain: str) -> List[Path]:
    """Write each ticket to ``<out_dir>/<KEY>.md`` plus an index and a starter AGENTS.md.

    Ticket files and the index are always (re)written. AGENTS.md is written only if it does
    not already exist, so a customized one is never clobbered on a re-run. Returns the paths written.
    """
    directory = Path(out_dir)
    directory.mkdir(parents=True, exist_ok=True)

    written: List[Path] = []
    for ticket in tickets:
        path = directory / f"{ticket.key}.md"
        path.write_text(render_ticket_md(ticket), encoding="utf-8")
        written.append(path)

    index = directory / "README.md"
    index.write_text(render_index_md(tickets), encoding="utf-8")
    written.append(index)

    agents = directory / "AGENTS.md"
    if not agents.exists():
        agents.write_text(starter_agents_md(domain), encoding="utf-8")
        written.append(agents)

    return written
